# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Vic Yeh
url:              http://vicyeh.com
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Vic Yeh
  url:            http://vicyeh.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars

twitter: https://twitter.com/vicoyeh
